language: java
jdk:
- openjdk8

addons:   
 sonarcloud:
  organization: "vincenzoviscontiii"
  token:
   secure: f3f743f0bae1587f4b124a59b38c0729782da010
      
script: 
- ant build 
- sonar-scanner

