language: java
jdk:
- openjdk8

addons:   
 sonarcloud:
  organization: "vincenzoviscontiii"
  token:
   secure: 0c71ad0906f373253f8b408ed5c84684cdb46f75
      
script: 
- ant build 
- sonar-scanner

